version: '3'
services:
  laser:
    image: laser:latest
    tty: true
    networks:
      - news-network
  news-database:
    build: database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - news-network
networks:
  news-network: