version: '3'
services:
  laser:
    image: laser:latest
    tty: true
  postgres-database:
    build: database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data